### ISSUE TITLE
Nightly builds started failing for the last week

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/ocean-bgc-cookbook#7]
**What happened**:

Dear authors (@rmshkv and @ kristenkrumhardt ), the nightly builds of this cookbook have been failing for the last week likely [due to a recently-broken URL](http://orca.science.oregonstate.edu/1080.by.2160.monthly.hdf.vgpm.m.chl.m.sst.php).  

Could you please have a look at it?

**Minimal Complete Verifiable Example**:

[Latest nightly build](https://github.com/ProjectPythia/ocean-bgc-cookbook/actions/runs/11656701097/job/32453179000) as of the creation of this issue.

**Anything else we need to know?**:

If you think it is due to Pythia infrastructure or something else other than the cookbook itself, please let us know.

**Comment by rmshkv** [comment]
Thanks for the heads up, @erogluorhan! I'll take a look and get it fixed this week.

**Comment by erogluorhan** [comment]
Thanks very much!

**Comment by erogluorhan** [comment]
I am closing this since apparently it was a one-time failure.
